[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
ffi = true
fs_permissions = [
    { access = "read", path = "./img/" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./lib/forge-devops" }
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config